Head:
  three_g:
    - 欸嘿
    - 我可是背了很多功课的
    - 这我肯定知道的嘛
  happy_answer:
    - 欸嘿嘿
    - 多好啊
  fear_answer:
    - emmmmm
    - 怪欸
    - 叉出去
  anger_answer:
    - 生气了哦
    - 哼!
  anonymous_answer:
    - 欸？
    - 我不认识你
    - 爬

Body:
  friends_message:  #勤奋蜂的成员介绍
  bees_message: #勤奋蜂的组织介绍
  threeG_url: https://www.zhihu.com/question/529411521 #3G故事的IP地址，爬一下？
  happy_answer: #开心倾向的回答
  fear_answer:  #害怕倾向的回答
  anger_answer: #生气倾向的回答
  anonymous_answer: #回答匿名对象

Tail:
  last: #存放语气或者表情